"""ERC-20 transfers with explicit allowances, gas strategy and broadcasting."""

from erc20_transfers.abi import (
    ALLOWANCE_SELECTOR,
    BALANCE_OF_SELECTOR,
    TRANSFER_FROM_SELECTOR,
    TRANSFER_SELECTOR,
    UINT256_MAX,
    decode_bool,
    decode_transfer_result,
    decode_uint256,
    encode_address,
    encode_allowance,
    encode_balance_of,
    encode_transfer,
    encode_transfer_from,
    encode_uint256,
    normalize_address,
)
from erc20_transfers.allowance import (
    UNLIMITED_ALLOWANCE,
    AllowanceCheck,
    InsufficientAllowance,
    check_allowance,
    encode_checked_transfer_from,
    require_allowance,
)
from erc20_transfers.gas import (
    BASE_FEE_MAX_CHANGE_DENOMINATOR,
    DEFAULT_HEADROOM_BLOCKS,
    ELASTICITY_MULTIPLIER,
    GWEI,
    MAX_HEADROOM_BLOCKS,
    Eip1559Fees,
    FeeCeilingTooLow,
    base_fee_headroom,
    estimate_fees,
    gwei,
    next_base_fee,
    priority_fee_from_history,
)
from erc20_transfers.units import (
    DECIMALS_SELECTOR,
    MAX_DECIMALS,
    TokenAmount,
    decode_decimals,
    encode_decimals,
    from_units,
    to_units,
)

__all__ = [
    "ALLOWANCE_SELECTOR",
    "AllowanceCheck",
    "BALANCE_OF_SELECTOR",
    "BASE_FEE_MAX_CHANGE_DENOMINATOR",
    "DECIMALS_SELECTOR",
    "DEFAULT_HEADROOM_BLOCKS",
    "ELASTICITY_MULTIPLIER",
    "Eip1559Fees",
    "FeeCeilingTooLow",
    "GWEI",
    "InsufficientAllowance",
    "MAX_DECIMALS",
    "MAX_HEADROOM_BLOCKS",
    "TRANSFER_FROM_SELECTOR",
    "TRANSFER_SELECTOR",
    "TokenAmount",
    "UINT256_MAX",
    "UNLIMITED_ALLOWANCE",
    "__version__",
    "base_fee_headroom",
    "check_allowance",
    "decode_bool",
    "decode_decimals",
    "decode_transfer_result",
    "decode_uint256",
    "encode_address",
    "encode_allowance",
    "encode_balance_of",
    "encode_checked_transfer_from",
    "encode_decimals",
    "encode_transfer",
    "encode_transfer_from",
    "encode_uint256",
    "estimate_fees",
    "from_units",
    "gwei",
    "next_base_fee",
    "normalize_address",
    "priority_fee_from_history",
    "require_allowance",
    "to_units",
]

__version__ = "0.1.0"
